wandb_version: 1

_fake_gpus:
  desc: null
  value: false
_tf_policy_handles_more_than_one_loss:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.20
    start_time: 1739471290
    t:
      1:
      - 1
      - 2
      - 3
      - 30
      - 55
      3:
      - 13
      - 14
      - 16
      4: 3.8.20
      5: 0.12.21
      8:
      - 6
      - 9
action_space:
  desc: null
  value: null
actions_in_input_normalized:
  desc: null
  value: false
batch_mode:
  desc: null
  value: truncate_episodes
clip_actions:
  desc: null
  value: false
clip_param:
  desc: null
  value: 0.2
clip_rewards:
  desc: null
  value: null
collect_metrics_timeout:
  desc: null
  value: 180
compress_observations:
  desc: null
  value: false
create_env_on_driver:
  desc: null
  value: false
custom_eval_function:
  desc: null
  value: null
custom_resources_per_worker:
  desc: null
  value: {}
date:
  desc: null
  value: 2025-02-14_00-06-34
eager_tracing:
  desc: null
  value: false
entropy_coeff:
  desc: null
  value: 0.01
entropy_coeff_schedule:
  desc: null
  value: null
env:
  desc: null
  value: fx-basic-v0-ppo
env_config:
  desc: null
  value:
    background_config: fx_basic
    background_config_extra_kvargs:
      book_log_depth: 10
      book_logging: false
      computation_delay: 0
      exchange_log_orders: false
      fundamental_file_path: /home/pietro/ucl-thesis-main/ucl-thesis-main/data/EURUSD_2024_01_midpoint_1000.pkl
      log_orders: false
      m_wake_up_freq: 0.5s
      mm_backstop_quantity: 0
      mm_cancel_limit_delay: 50
      mm_level_spacing: 5
      mm_min_order_size: 3
      mm_num_ticks: 5
      mm_pov: 0.025
      mm_price_skew: 4
      mm_skew_beta: 0
      mm_spread_alpha: 0.75
      mm_wake_up_freq: 0.1s
      mm_window_size: adaptive
      num_mm: 2
      num_momentum_agents: 40
      num_noise_agents: 5000
      num_value_agents: 200
      seed: 1
      starting_cash: 2000000
      ticker: EURUSD
      val_kappa: 1.67e-15
      val_lambda_a: 7.0e-11
      val_vol: 1.0e-08
      val_wake_up_freq: 60s
    debug_mode: true
    dirichlet_a_h: 5.0
    dirichlet_a_l: 1.0
    dirichlet_k: 5.0e-05
    dirichlet_steps_ahead: 8
    first_interval: 00:00:30
    kappa: 10
    market_data_buffer_length: 5
    max_holdings: 10
    order_fixed_size: 1
    reduction_factor: 0.99996
    starting_cash: 2000000
    state_history_length: 2
    state_timesteps_back: 0
    timestep_duration: 0.2s
    w_direc: 1.0
env_task_fn:
  desc: null
  value: null
evaluation_config:
  desc: null
  value: {}
evaluation_interval:
  desc: null
  value: null
evaluation_num_episodes:
  desc: null
  value: 10
evaluation_num_workers:
  desc: null
  value: 0
evaluation_parallel_to_training:
  desc: null
  value: false
experiment_id:
  desc: null
  value: 781952807d624948965bfaa1bad68648
exploration_config:
  desc: null
  value:
    type: StochasticSampling
explore:
  desc: null
  value: true
extra_python_environs_for_driver:
  desc: null
  value: {}
extra_python_environs_for_worker:
  desc: null
  value: {}
fake_sampler:
  desc: null
  value: false
framework:
  desc: null
  value: torch
gamma:
  desc: null
  value: 0.99
grad_clip:
  desc: null
  value: null
horizon:
  desc: null
  value: null
hostname:
  desc: null
  value: DESKTOP-CF5IBD6
ignore_worker_failures:
  desc: null
  value: false
in_evaluation:
  desc: null
  value: false
input:
  desc: null
  value: sampler
input_config:
  desc: null
  value: {}
input_evaluation:
  desc: null
  value:
  - is
  - wis
kl_coeff:
  desc: null
  value: 0.2
kl_target:
  desc: null
  value: 0.01
lambda:
  desc: null
  value: 0.95
local_tf_session_args:
  desc: null
  value:
    inter_op_parallelism_threads: 8
    intra_op_parallelism_threads: 8
log_level:
  desc: null
  value: WARN
log_sys_usage:
  desc: null
  value: true
logger_config:
  desc: null
  value: null
lr:
  desc: null
  value: 3.0e-05
lr_schedule:
  desc: null
  value: null
metrics_smoothing_episodes:
  desc: null
  value: 100
min_iter_time_s:
  desc: null
  value: 1
model:
  desc: null
  value:
    _no_preprocessing: false
    _time_major: false
    _use_default_native_models: false
    attention_dim: 64
    attention_head_dim: 32
    attention_init_gru_gate_bias: 2.0
    attention_memory_inference: 50
    attention_memory_training: 50
    attention_num_heads: 1
    attention_num_transformer_units: 1
    attention_position_wise_mlp_dim: 32
    attention_use_n_prev_actions: 0
    attention_use_n_prev_rewards: 0
    conv_activation: relu
    conv_filters: null
    custom_action_dist: null
    custom_model: null
    custom_model_config: {}
    custom_preprocessor: null
    dim: 84
    fcnet_activation: tanh
    fcnet_hiddens:
    - 128
    - 128
    framestack: true
    free_log_std: false
    grayscale: false
    lstm_cell_size: 256
    lstm_use_prev_action: false
    lstm_use_prev_action_reward: -1
    lstm_use_prev_reward: false
    max_seq_len: 20
    no_final_linear: false
    post_fcnet_activation: relu
    post_fcnet_hiddens: []
    use_attention: false
    use_lstm: false
    vf_share_layers: false
    zero_mean: true
monitor:
  desc: null
  value: -1
multiagent:
  desc: null
  value:
    count_steps_by: env_steps
    observation_fn: null
    policies:
      default_policy: PolicySpec(policy_class=None, observation_space=None, action_space=None,
        config={})
    policies_to_train: null
    policy_map_cache: null
    policy_map_capacity: 100
    policy_mapping_fn: null
    replay_mode: independent
no_done_at_end:
  desc: null
  value: false
node_ip:
  desc: null
  value: 172.22.51.105
normalize_actions:
  desc: null
  value: true
num_cpus_for_driver:
  desc: null
  value: 1
num_cpus_per_worker:
  desc: null
  value: 1
num_envs_per_worker:
  desc: null
  value: 1
num_gpus:
  desc: null
  value: 0
num_gpus_per_worker:
  desc: null
  value: 0
num_sgd_iter:
  desc: null
  value: 10
num_workers:
  desc: null
  value: 0
observation_filter:
  desc: null
  value: MeanStdFilter
observation_space:
  desc: null
  value: null
optimizer:
  desc: null
  value: {}
output:
  desc: null
  value: null
output_compress_columns:
  desc: null
  value:
  - obs
  - new_obs
output_max_file_size:
  desc: null
  value: 67108864
pid:
  desc: null
  value: 77254
placement_strategy:
  desc: null
  value: PACK
postprocess_inputs:
  desc: null
  value: false
preprocessor_pref:
  desc: null
  value: deepmind
record_env:
  desc: null
  value: false
remote_env_batch_wait_ms:
  desc: null
  value: 0
remote_worker_envs:
  desc: null
  value: false
render_env:
  desc: null
  value: false
rollout_fragment_length:
  desc: null
  value: 200
sample_async:
  desc: null
  value: false
sample_collector:
  desc: null
  value: <class 'ray.rllib.evaluation.collectors.simple_list_collector.SimpleListCollector'>
seed:
  desc: null
  value: 1
sgd_minibatch_size:
  desc: null
  value: 128
shuffle_buffer_size:
  desc: null
  value: 0
shuffle_sequences:
  desc: null
  value: true
simple_optimizer:
  desc: null
  value: false
soft_horizon:
  desc: null
  value: false
synchronize_filters:
  desc: null
  value: true
tf_session_args:
  desc: null
  value:
    allow_soft_placement: true
    device_count:
      CPU: 1
    gpu_options:
      allow_growth: true
    inter_op_parallelism_threads: 2
    intra_op_parallelism_threads: 2
    log_device_placement: false
timesteps_per_iteration:
  desc: null
  value: 1000
train_batch_size:
  desc: null
  value: 4000
trial_id:
  desc: null
  value: 46b89_00000
use_critic:
  desc: null
  value: true
use_gae:
  desc: null
  value: true
vf_clip_param:
  desc: null
  value: 200.0
vf_loss_coeff:
  desc: null
  value: 1.0
vf_share_layers:
  desc: null
  value: -1
